// declare all action type names here

export const LOGIN_REQUEST = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FORGET_REQUEST = 'FORGET_REQUEST';
export const FORGET_PWD_SUCCESS = 'FORGET_PWD_SUCCESS';
export const FORGET_PWD_FAILURE = 'FORGET_PWD_FAILURE';
export const FORGET_CLR_RESPONSE = 'FORGET_CLR_RESPONSE';
export const FORGET_PWD_CALL = 'FORGET_PWD_CALL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';

export const GOAL_SELECT = 'GOAL_SELECT';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const REGISTRATION_REQUEST=  'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS= 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE= 'REGISTRATION_FAILURE';

export const REGISTRATION_AUTH= 'REGISTRATION_AUTH';

export const HOMESCREEN_DATA= 'HOMESCREEN_DATA';
export const HOME_USERS= 'HOME_USERS';
export const HOME_SUCCESS= 'HOME_SUCCESS';
export const HOME_FAILURE= 'HOME_FAILURE';
export const HOME_USERS_SUCCESS= 'HOME_USERS_SUCCESS';



export const HOME_LISTING_SUCCESS= 'HOME_LISTING_SUCCESS';
export const HOMELISTINGSCREEN_DATA= 'HOMELISTINGSCREEN_DATA';
export const HOME_LISTING_USERS= 'HOME_LISTING_USERS';
export const HOME_LISTING_FAILURE= 'HOME_LISTING_FAILURE';

export const LIKE_USER= 'LIKE_USER';
export const LIKE_USER_SUCCESS='LIKE_USER_SUCCESS';
export const LIKE_USER_FAILURE='LIKE_USER_FAILURE';

export const DISLIKE_USER='DISLIKE_USER';
export const DISLIKE_USER_SUCCESS='DISLIKE_USER_SUCCESS';
export const DISLIKE_USER_FAILURE='DISLIKE_USER_FAILURE';

export const PROFILE_EDIT_JSON = 'PROFILE_EDIT_JSON';


export const PROFILE_LIST_UPDATE = 'PROFILE_LIST_UPDATE';
export const PROFILE_LIST_UPDATE_SUCCESS = 'PROFILE_LIST_UPDATE_SUCCESS';
export const PROFILE_LIST_UPDATE_FAILURE = 'PROFILE_LIST_UPDATE_FAILURE';
export const GOAL_REQUEST = 'GOAL_REQUEST';
export const GOAL_SUCCESS = 'GOAL_SUCCESS';
export const GOAL_FAILURE = 'GOAL_FAILURE';


export const PROFILE_VIEW_REQUEST = 'PROFILE_VIEW_REQUEST';
export const PROFILE_VIEW_SUCCESS = 'PROFILE_VIEW_SUCCESS';
export const PROFILE_VIEW_FAILURE = 'PROFILE_VIEW_FAILURE';

export const PROFILE_PROMPT_UPDATE = 'PROFILE_PROMPT_UPDATE';
export const PROFILE_PROMPT_UPDATE_SUCCESS = 'PROFILE_PROMPT_UPDATE_SUCCESS';
export const PROFILE_PROMPT_UPDATE_FAILURE = 'PROFILE_PROMPT_UPDATE_FAILURE';

export const PROFILE_PROMPT_DELETE = 'PROFILE_PROMPT_DELETE';
export const PROFILE_PROMPT_DELETE_SUCCESS = 'PROFILE_PROMPT_DELETE_SUCCESS';
export const PROFILE_PROMPT_DELETE_FAILURE = 'PROFILE_PROMPT_DELETE_FAILURE';

export const PROFILE_MEDIA_UPDATE = 'PROFILE_MEDIA_UPDATE';
export const PROFILE_MEDIA_SUCCESS = 'PROFILE_MEDIA_SUCCESS';
export const PROFILE_MEDIA_FAILURE = 'PROFILE_MEDIA_FAILURE';

export const PROFILE_MEDIA_DELETE = 'PROFILE_MEDIA_DELETE';
export const PROFILE_MEDIA_DELETE_SUCCESS = 'PROFILE_MEDIA_DELETE_SUCCESS';
export const PROFILE_MEDIA_DELETE_FAILURE = 'PROFILE_MEDIA_DELETE_FAILURE';

export const ADDLISTING_REQUEST='ADDLISTING_REQUEST';
export const ADDLISTING_SUCCESS='ADDLISTING_SUCCESS';
export const ADDLISTING_FAILURE="ADDLISTING_FAILURE";
export const ADDLISTING_CHANGE='ADDLISTING_CHANGE';

export const LISTING_REQUEST='LISTING_REQUEST';
export const LISTING_SUCCESS='LISTING_SUCCESS';
export const LISTING_FAILURE='LISTING_FAILURE';

export const LISTING_LIKE_REQUEST='LISTING_LIKE_REQUEST';
export const LISTING_LIKE_SUCCESS='LISTING_LIKE_SUCCESS';
export const LISTING_LIKE_FAILURE='LISTING_LIKE_FAILURE';

export const UPDATELISTING_REQUEST = 'UPDATELISTING_REQUEST';
export const UPDATELISTING_SUCCESS = 'UPDATELISTING_SUCCESS';
export const UPDATELISTING_FAILURE = 'UPDATELISTING_FAILURE';

export const DELETELISTING_REQUEST = 'DELETELISTING_REQUEST';
export const DELETELISTING_SUCCESS = 'DELETELISTING_SUCCESS';
export const DELETELISTING_FAILURE = 'DELETELISTING_FAILURE';

export const LISTINGS_MEDIA_UPDATE = 'LISTINGS_MEDIA_UPDATE';
export const LISTINGS_MEDIA_SUCCESS = 'LISTINGS_MEDIA_SUCCESS';
export const LISTINGS_MEDIA_FAILURE = 'LISTINGS_MEDIA_FAILURE';

export const LISTINGS_MEDIA_DELETE = 'LISTINGS_MEDIA_DELETE';
export const LISTINGS_MEDIA_DELETE_SUCCESS = 'LISTINGS_MEDIA_DELETE_SUCCESS';
export const LISTINGS_MEDIA_DELETE_FAILURE = 'LISTINGS_MEDIA_DELETE_FAILURE';

export const VIEWLISTING_REQUEST = 'VIEWLISTING_REQUEST';
export const VIEWLISTING_SUCCESS = 'VIEWLISTING_SUCCESS';
export const VIEWLISTING_FAILURE = 'VIEWLISTING_FAILURE';

export const EDITLISTING_REQUEST = 'EDITLISTING_REQUEST';
export const GETSTARTED_REQUEST = 'GETSTARTED_REQUEST';
export const LISTING_LIKE = 'LISTING_LIKE';

export const LOGIN_USER='LOGIN_USER';
export const LOGGED_IN_SUCCESS=' LOGGED_IN_SUCCESS';

export const SEND_USER='SEND_USER';
export const SENT_USER_SUCCESS='SENT_USER_SUCCESS';

export const CHAT_WITH_USER='CHAT_WITH_USER';
export const CHAT_HISTORY_SUCCESS='CHAT_HISTORY_SUCCESS';

export const FROM_USER_ID='FROM_USER_ID'

export const SEND_MESSAGES='SEND_MESSAGES'
export const SEND_MESSAGE_SUCCESS='SEND_MESSAGE_SUCCESS'


export const LIKE_LISTING= 'LIKE_LISTING';
export const LIKE_LISTING_SUCCESS='LIKE_LISTING_SUCCESS';
export const LIKE_LISTING_FAILURE='LIKE_LISTING_FAILURE';

export const DISLIKE_LISTING='DISLIKE_LISTING';
export const DISLIKE_LISTING_SUCCESS='DISLIKE_LISTING_SUCCESS';
export const DISLIKE_LISTING_FAILURE='DISLIKE_LISTING_FAILURE';
export const PENDING_REQUEST_ID='PENDING_REQUEST_ID'
export const PENDING_REQUEST_ID_SUCCESS='PENDING_REQUEST_ID_SUCCESS'
export const REQUEST_USER_DETAILS_SUCCESS='REQUEST_USER_DETAILS_SUCCESS';
export const REQUEST_SENT_ID='REQUEST_SENT_ID';
export const REQ_USER_DETAILS_SUCCESS='REQ_USER_DETAILS_SUCCESS';
export const REQUEST_SENT_ID_SUCCESS='REQUEST_SENT_ID_SUCCESS';
export const REQUEST_LISTING_ID='REQUEST_LISTING_ID';
export const REQUEST_LIST_ID_SUCCESS='REQUEST_LIST_ID_SUCCESS';
export const REQ_LIST_DETAILS_SUCCESS='REQ_LIST_DETAILS_SUCCESS';
export const ACCEPT_REQUEST='ACCEPT_REQUEST'
export const REJECT_REQUEST='REJECT_REQUEST'
export const LIKE_LIST='LIKE_LIST'



export const PROFILE_MODAL_VIEW='PROFILE_MODAL_VIEW';
export const PROFILE_MODAL_VIEW_SUCCESS='PROFILE_MODAL_VIEW_SUCCESS';
export const PROFILE_MODAL_VIEW_FAILURE='PROFILE_MODAL_VIEW_FAILURE';

export const PROFILE_MODAL_LIST_VIEW='PROFILE_MODAL_LIST_VIEW';
export const PROFILE_MODAL_LIST_VIEW_SUCCESS='PROFILE_MODAL_LIST_VIEW_SUCCESS';
export const PROFILE_MODAL_LIST_VIEW_FAILURE='PROFILE_MODAL_LIST_VIEW_FAILURE';

export const CHATLIST_DATA='CHATLIST_DATA';
export const CHATLIST_SUCCESS='CHATLIST_SUCCESS';
export const CHATLIST_FAILURE='CHATLIST_FAILURE';

export const PREFERENCE_VIEW_REQUEST='PREFERENCE_VIEW_REQUEST';
export const PREFERENCE_VIEW_SUCCESS='PREFERENCE_VIEW_SUCCESS';
export const PREFERENCE_VIEW_FAILURE='PREFERENCE_VIEW_FAILURE';

export const PREFERENCE_LIST_UPDATE='PREFERENCE_LIST_UPDATE';
export const PREFERENCE_LIST_UPDATE_SUCCESS='PREFERENCE_LIST_UPDATE_SUCCESS';
export const PREFERENCE_LIST_UPDATE_FAILURE='PREFERENCE_LIST_UPDATE_FAILURE';

export const GOAL_CHANGE_REQUEST='GOAL_CHANGE_REQUEST';
export const GOAL_CHANGE_SUCCESS='GOAL_CHANGE_SUCCESS';
export const GOAL_CHANGE_FAILURE='GOAL_CHANGE_FAILURE';
export const GET_FRIENDS_LIST='GET_FRIENDS_LIST';
export const GET_FRIENDS_LIST_SUCCESS='GET_FRIENDS_LIST_SUCCESS';
export const GET_FRIENDS_LIST_ERROR='GET_FRIENDS_LIST_ERROR';

export const GET_FRIEND_PROFILE='GET_FRIEND_PROFILE';
export const GET_FRIEND_PROFILE_SUCCESS='GET_FRIEND_PROFILE_SUCCESS';
export const GET_FRIEND_PROFILE_ERROR='GET_FRIEND_PROFILE_ERROR';

export const DO_UN_FRIEND='DO_UN_FRIEND';
export const DO_UN_FRIEND_SUCCESS='DO_UN_FRIEND_SUCCESS';
export const DO_UN_FRIEND_ERROR='DO_UN_FRIEND_ERROR';


export const PENDING_REQUEST_ID_FAILURE='PENDING_REQUEST_ID_FAILURE';
export const REQUEST_USER_DETAILS_FAILURE='REQUEST_USER_DETAILS_FAILURE'
export const ACCOUNT_DEACTIVATE_REQUEST='PROFILE_DEACTIVATE_REQUEST';
export const ACCOUNT_DEACTIVATE_SUCCESS='PROFILE_DEACTIVATE_SUCCESS';
export const ACCOUNT_DEACTIVATE_ERROR='PROFILE_DEACTIVATE_ERROR';
export const REQUEST_SENT_ID_FAILURE='REQUEST_SENT_ID_FAILURE';
export const REQ_USER_DETAILS_FAILURE='REQ_USER_DETAILS_FAILURE';
export const REQUEST_LIST_ID_FAILURE='REQUEST_LIST_ID_FAILURE';
export const REQ_LIST_DETAILS_FAILURE='REQ_LIST_DETAILS_FAILURE';
export const GET_PROFILE_MODAL='GET_PROFILE_MODAL';
export const GET_PROFILE_MODAL_SUCCESS='GET_PROFILE_MODAL_SUCCESS';
export const GET_PROFILE_MODAL_ERROR='GET_PROFILE_MODAL_ERROR';
export const CLEAR_PROFILE_MODAL='CLEAR_PROFILE_MODAL';
export const CONFIRM_ROOMMATE='CONFIRM_ROOMMATE';
export const CONFIRM_ROOMMATE_LOAD_SUCCESS='CONFIRM_ROOMMATE_LOAD_SUCCESS'
export const CONFIRM_ROOMMATE_LOAD_FAILURE='CONFIRM_ROOMMATE_LOAD_FAILURE';
export const CLEAR_STATE='CLEAR_STATE';
export const CONFIRM_TENANT='CONFIRM_TENANT';
export const CONFIRM_LISTING_REQUEST='CONFIRM_LISTING_REQUEST';
export const LOAD_LISTING='LOAD_LISTING';
export const LOAD_LISTING_SUCCESS='LOAD_LISTING_SUCCESS';
export const LISTINGSS_SUCCESS='LISTINGSS_SUCCESS';
export const GET_PROFILE_DATA='GET_PROFILE_DATA';
export const ADD_TENANATS_REQUEST='ADD_TENANATS_REQUEST';
export const ADD_TENANATS_SUCCESS='ADD_TENANATS_SUCCESS';
export const ADD_TENANATS_FAILURE='ADD_TENANATS_FAILURE';
export const CONFIRM_LIST='CONFIRM_LIST';
export const ROOMMATE_LIST_SUCCESS='ROOMMATE_LIST_SUCCESS';
export const GET_ROOMMATE_PROFILE='GET_ROOMMATE_PROFILE';
export const GET_ROOMMATE_PROFILE_ERROR='GET_ROOMMATE_PROFILE_ERROR';
export const GET_ROOMMATE_ERROR='GET_ROOMMATE_ERROR';
export const GET_ROOMMATE_PROFILE_SUCCESS='GET_ROOMMATE_PROFILE_SUCCESS';
export const REMOVEROOMMATE='REMOVEROOMMATE'
export const CONFIRMED_USERS_REQUEST='CONFIRMED_USERS_REQUEST';
export const CONFIRMED_USERS_SUCCESS='CONFIRMED_USERS_SUCCESS';
export const CONFIRMED_USERS_FAILURE='CONFIRMED_USERS_FAILURE';
export const CONFIRMED_USER_PROFILE_DATA='CONFIRMED_USER_PROFILE_DATA';
export const UNCONFIRMED_USER='UNCONFIRMED_USER';
export const RELIST_REQUEST='RELIST_REQUEST';
export const RELIST_SUCCESS='RELIST_SUCCESS';
export const RELIST_FAILURE='RELIST_FAILURE';